server-config:
  host: 0.0.0.0
  port: 8888
  schema: http
  domain: 127.0.0.1
  server: waitress
  service-package: service
  view-package: view
  service-js-path: view/service.js
  service-js-template: |
    //init service function
    function initService(serviceName) {
        var variables = serviceName.split('.');
        var p = window;
        for (var i = 0; i < variables.length; i++) {
            var v = variables[i];
            p[v] = p[v] || {};
            p = p[v];
        }
    }

    //execute service function
    function executeService(serviceName, data, success, error) {
        var xhr = new XMLHttpRequest();
        var formData = new FormData();
        for(var key in data) { formData.append(key, data[key]); }
        success = success || function (data) {};
        error = error || function (e) { console.error(e) };
        xhr.onreadystatechange = function () {
            if (xhr.readyState == 4) {
                if (xhr.status == 200) {
                    var r = eval('('+xhr.response+')');
                    if(r.code == 200){
                        success(r.data);
                    } else {
                        error(r.message);
                    }
                } else {
                    error(xhr.response);
                }
            }
        }
        xhr.open("POST", basePath + serviceName.replace(/\./g, '/'), true);
        xhr.send(formData);
    }

window-config:
  args:
    - easy-window.exe
    - -url view/index.html
    - -title 测试程序
    - -icon favicon.ico
    - -width 800
    - -height 600
    - -timeout 5000

