args:
  - easy-window.exe
#  - -url "view/index.html\?port=3000"
  - -url "http://jeasyui.com/demo-vue/main/index.php"
  - -title 测试程序
  - -icon favicon.ico
  - -width 800
  - -height 600
  - -timeout 5000
  - -contextmenu true

