args:
  - easy-window.exe
  - -url "./view/index.html"
#  - -url "http://www.baidu.com?a=123"
  - -title 测试程序
  - -icon favicon.ico
  - -width 800
  - -height 600
  - -timeout 5000
  - -contextmenu true

